[package]
name = "spiral"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.14.3", features = ["raw"] }
image = "0.25.0"
rand = "0.8.5"
twox-hash = "1.6.3"
